version: '3.5'

networks:
  postgres:
    driver: bridge

services:

  core-service-app:
    image: core-service-app
    environment:
      DATASOURCE_USERNAME: ${DATASOURCE_USER:postgres}
      SPRING_URL: ${DATASOURCE_URL:jdbc:postgresql://core-service-postgres:5432/postgres}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASS:postgres}
    ports:
      - '8080:8080'
    networks:
      - postgres