spring:
  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    username: ${DATASOURCE_USERNAME:postgres}
    url: jdbc:postgresql://localhost:5432/postgres
    password: ${DATASOURCE_PASSWORD:postgres}
