CREATE DATABASE core_service;
GRANT ALL PRIVILEGES ON DATABASE core_service TO postgres;
CREATE USER keycloak WITH PASSWORD 'keycloak';
CREATE DATABASE keycloak;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
CREATE DATABASE sonar;
GRANT ALL PRIVILEGES ON DATABASE sonar TO postgres;
